### PR TITLE
Duck type room messages to m.text if possible

### PR DESCRIPTION
**Pull request by LorenDB**
nheko PR will come after this is merged

### CODE REVIEW

**Comment by deepbluev7** [comment]
But can't you already do `json(unknown_event.original_content)["content"]["body"]`?

**Comment by LorenDB** [comment]
Well, you might be able to, but that would create interesting problems at other places, since the Unknown struct is used to represent all unknown events, not just messages with unknown msgtypes. That would make it a lot more complex to successfully parse the unknown messages later and would also be a problem when trying to make the MessageDelegate choose the right delegate for the unknown message.

**Comment by deepbluev7** [comment]
It however doesn't break persisting unknown events and then being able to access them after an update. I also don't see much of an issue with the delegate, since it is just a text delegate in both cases still.

**Comment by LorenDB** [comment]
Superseded by #92

**Pull request closed without merging**
