### PR TITLE
Support registration token UIA type

### PR DESCRIPTION
**Pull request by govynnus**
MSC3231: https://github.com/matrix-org/matrix-doc/pull/3231

### CODE REVIEW

**Comment by govynnus** [comment]
Not entirely sure I haven't missed something, but I couldn't see any other obvious places additions would be needed

**Comment by redsky17** [comment]
So I think this covers everything from the perspective of recognizing the new flow type from the server and also sending the appropriate registration request back.  I do know on your MSC proposal, you suggested a validity URL as well.  I'm not sure the status of that specific part being included in the final MSC or not, but it might be good to add the piping for that to mtxclient as well.

@deepbluev7 , can you verify that I didn't miss anything?  You've spent a lot more time on auth flows than I have =D.

**Comment by govynnus** [comment]
@redsky17 Oh I completely forgot about the validity checking endpoint :D

**Comment by deepbluev7** [comment]
These changes look correct to me. Maybe we are missing something, but we can add that, when the code is actually used in Nheko. The validity checking can be done in a separate PR imo. Thank you!

**Pull request merged**
